---
apiVersion: v1
kind: Application
metadata:
  name: eshopapplication
  labels:
    app: eshopapplication
spec:
  type: NodePort
  selector:
    app: eshopapplication
  ports:
  - protocol: TCP
    port: 5050
    name: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: shopfront
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: danielbryantuk/djshopfront:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          timeoutSeconds: 1
