---
apiVersion: v1
kind: Service
metadata:
  name: eshopapplication
  labels:
    app: eshopapplication
spec:
  type: NodePort
  selector:
    app: eshopapplication
  ports:
  - protocol: TCP
    port: 8010
    name: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: eshopapplication
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eshopapplication
    spec:
      containers:
      - name: eshopapplication
        image: zambosss1/kiii_project:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          timeoutSeconds: 1
