---
apiVersion: v1
kind: Service
metadata:
  name: EShopApp
  labels:
    app: EShopApp
spec:
  type: NodePort
  selector:
    app: EShopApp
  ports:
  - protocol: TCP
    port: 8010
    name: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: EShopApp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: EShopApp
    spec:
      containers:
      - name: EShopApp
        image: zambosss1/kiii_project:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          timeoutSeconds: 1
